### ISSUE TITLE
Error backup with table '.inner.test_table'

### ISSUE THREAD

**Issue by molchanovdp** [Altinity/clickhouse-backup#28]
Hello!
Clickhouse version 19.1.8

When creating a backup request failed:

`can't freeze partition '0590dc88487514d92e90360839939c5f' on 'default..inner.test_table' with: code: 62, message: Syntax error: failed at position 21: .inner.test_table FREEZE PARTITION ID '0590dc88487514d92e90360839939c5f';. Expected identifier`

It may be worth escaping the name of the table with ``?

**Comment by AlexAkulov** [comment]
It's a good proposal!

**Comment by AlexAkulov** [comment]
Unfortunately it's not as easy as it seems.

**Comment by molchanovdp** [comment]
But I think it is worth doing it, otherwise quite often similar problems will arise. Here is another example, here the table name starts with a number. So it does not work either.
```
can't freeze partition '20170626' on 'default.2table' with: code: 62, message: Syntax error: failed at position 21: 2table FREEZE PARTITION ID '20170626';. Wrong number

```

**Comment by molchanovdp** [comment]
As I understand it, this is already fixed in the https://github.com/AlexAkulov/clickhouse-backup/commit/ba996f192feefe1f5e395c0e931fda89d258b13a
I checked and no errors occur

**Comment by AlexAkulov** [comment]
No. These changes fixed 'freeze' command but 'create' and 'restore' still don't work. This is related to how ClickhHouse encode special characters in paths on filesystem. For example, table with name '.table1' will be saved on FS as '%2Etable' but clickhouse-backup does't expect this.

**Comment by mrtarsa** [comment]
We experience the same problem. Any progress on this?

**Comment by AlexAkulov** [comment]
It must be fixed in v0.4.0. Please check it.
